# yaml 配置  mysql 跟  blog-service服务
version: "3.7"
services:
  mysql:
    image: "mysql:5.7.22"
    ports:
      - "33061:3306"
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "blog_service"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_HOST: '%'
    container_name: mysql
    volumes:
      - ./docs/mysql:/var/lib/mysql
      - ./docs/sql/blog_service.sql:/docker-entrypoint-initdb.d/blog.sql
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    networks:
      - blog-net
  blog:
    container_name: blog
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./wait-for-it.sh:/wait-for-it.sh"
    depends_on:
      - mysql
    command: >
      /bin/bash -c '
      while ! nc -z database 3306;
      do
       echo "wait for database";
       sleep 1;
      done;

      echo "database is ready!";
      echo "start web service here";
      '
    ports:
      - "8889:8888"
    expose:
      - 8889
    privileged: true
    networks:
      - blog-net
networks:
  blog-net:
    driver: "bridge"