# yaml 配置  mysql 跟  blog-service服务
version: "3.7"
services:
  blog:
    restart: always
    container_name: blog
    build: .
    command: sh -c "./wait-for-it.sh mysql:3306 -- ./blog-service"
    depends_on:
      - mysql
    ports:
      - "8889:8000"
    expose:
      - "8889"
    privileged: true
  mysql:
    container_name: mysql
    image: "mysql:5.7.22"
    ports:
      - "33061:3306"
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "blog_service"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./docs/mysql:/var/lib/mysql
      - ./docs/sql/blog_service.sql:/docker-entrypoint-initdb.d/blog.sql
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
