# yaml 配置  mysql 跟  blog-service服务
version: "3.7"
services:
  mysql:
    image: "mysql:5.7.22"
    ports:
      - "3306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/blog_service.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "blog-service"
      MYSQL_PASSWORD: "root"
    volumes:
      - ./docs/sql/blog_service.sql:/data/blog_service.sql
  blog:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    ports:
      - "8888:8888"